###
GET http://localhost:8080/api/movies
Accept: application/json

###
POST http://localhost:8080/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Anyámék a havon",
  "length": 95
}

###
POST http://localhost:8080/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Köszi a csokit",
  "length": 85
}

###
GET http://localhost:8080/api/movies/2
Accept: application/json

###
GET http://localhost:8080/api/movies/22
Accept: application/json

###
GET http://localhost:8080/api/movies/2/ratings
Accept: application/json

###
GET http://localhost:8080/api/movies/22/ratings
Accept: application/json

###
POST http://localhost:8080/api/movies/2/ratings
Content-Type: application/json
Accept: application/json

{
  "rating": 5
}

###
POST http://localhost:8080/api/movies/2/ratings
Content-Type: application/json
Accept: application/json

{
  "rating": 4
}

###
POST http://localhost:8080/api/movies/2/ratings
Content-Type: application/json
Accept: application/json

{
  "rating": 3
}
