POST http://localhost:8080/api/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "Toyota",
  "type": "Corolla",
  "age": 15,
  "condition": "EXCELLENT",
  "kmCounter": 95000
}

###
POST http://localhost:8080/api/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "BMW",
  "type": "x3",
  "age": 19,
  "condition": "NORMAL",
  "kmCounter": 350000
}

###
POST http://localhost:8080/api/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "Toyota",
  "type": "Corolla",
  "age": 25,
  "condition": "POOR",
  "kmCounter": 295000
}

###
POST http://localhost:8080/api/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "Toyota",
  "type": "Auris",
  "age": 5,
  "condition": "EXCELLENT",
  "kmCounter": 55892
}

###
GET http://localhost:8080/api/cars
Accept: application/json

###
GET http://localhost:8080/api/cars?OrderBy=km&OrderType=desc
Accept: application/json

###

GET http://localhost:8080/api/cars?OrderBy=km&OrderType=asc
Accept: application/json

###
GET http://localhost:8080/api/cars?OrderBy=age&OrderType=desc
Accept: application/json

###

GET http://localhost:8080/api/cars?OrderBy=age&OrderType=asc
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=toyota
Accept: application/json

###
GET http://localhost:8080/api/cars?maxAge=20
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&maxAge=17
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&OrderBy=km
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&OrderBy=km&OrderType=desc
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&maxAge=15&OrderBy=km&OrderType=desc
Accept: application/json

###
GET http://localhost:8080/api/cars/brands
Accept: application/json

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": 396230
}

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": 6230
}

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": -6230
}

###
GET http://localhost:8080/api/cars/1
Accept: application/json

###
DELETE http://localhost:8080/api/cars/269
Content-Type: application/json
Accept: application/json

###
